spring.application.name=UcMarket

spring.datasource.url=jdbc:postgresql://localhost:5432/UCMARKETV2
spring.datasource.username=postgres
spring.datasource.password=zxc123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true